[package]
name = "letlang_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
tokio = { version = "1.20", features = ["full"] }
genawaiter = "0.99"
uuid = { version = "1.1", features = ["v4"] }
