[package]
name = "hello-world"
version = "0.0.0"
description = "Hello world example in Letlang"

[executable]
bin = "hello"
module = "hello.main"

[toolchain]
letlang = "0.1.0"
rust = "2021"

[dependencies]
