[package]
name = "typechecks"
version = "0.0.0"
description = "Type check examples in Letlang"

[executable]
bin = "typecheck"
module = "typecheck.main"

[toolchain]
letlang = "0.1.0"
rust = "2021"

[dependencies]
