[package]
name = "fibo"
version = "0.0.0"
description = "Exemple of fibonacci implementation"

[executable]
bin = "fibo"
module = "fibo::main"

[toolchain]
letlang = "0.1.0"
rust = "2021"

[dependencies]
stdlib = { path = "../../lib" }
