[package]
name = "letlang_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
letlang_parser = { path = "../letlang_parser" }

string-interner = "0.14"
askama = "0.11"

serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
