[package]
name = "letlang_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
letlang_compiler = { path = "../letlang_compiler" }

serde = { version = "1.0", features = ["derive"] }
toml = "0.5"

walkdir = "2.3"

clap = { version = "3.2", features = ["cargo", "derive"] }
